
[Drinks]
	#Defines items that will recover thirst when drunk
	#Format: [["item-id-1", hydration-amount, quenching-amount], ["item-id-2", hydration-amount, quenching-amount], ...etc]
	drinks = [[["minecraft:milk_bottle", 6, 8], ["minecraft:milk_bucket", 3, 6], ["minecraft:water_bucket", 3, 6], ["minecraft:potion", 6, 8], ["thirst:terracotta_water_bowl", 4, 5], ["farmersrespite:green_tea", 10, 14], ["farmersrespite:long_green_tea", 10, 14], ["farmersrespite:strong_green_tea", 10, 14], ["farmersrespite:yellow_tea", 10, 14], ["farmersrespite:long_yellow_tea", 10, 14], ["farmersrespite:strong_yellow_tea", 10, 14], ["farmersrespite:black_tea", 10, 14], ["farmersrespite:long_black_tea", 10, 14], ["farmersrespite:strong_black_tea", 10, 14], ["farmersrespite:rose_hip_tea", 12, 22], ["farmersrespite:long_rose_hip_tea", 12, 22], ["farmersrespite:strong_rose_hip_tea", 12, 22], ["farmersrespite:dandelion_tea", 12, 22], ["farmersrespite:long_dandelion_tea", 12, 22], ["farmersrespite:strong_dandelion_tea", 12, 22], ["farmersrespite:gamblers_tea", 6, 11], ["farmersrespite:long_gamblers_tea", 6, 11], ["farmersrespite:strong_gamblers_tea", 6, 11], ["farmersrespite:coffee", 6, 11], ["farmersrespite:long_coffee", 6, 11], ["farmersrespite:stong_coffee", 6, 11], ["farmersrespite:strong_melon_juice", 8, 13], ["farmersrespite:strong_apple_cider", 8, 13], ["create:builders_tea", 12, 22], ["farmersdelight:apple_cider", 8, 13], ["farmersdelight:melon_juice", 8, 13], ["brewinandchewin:beer", 10, 14], ["brewinandchewin:vodka", 10, 14], ["brewinandchewin:rice_wine", 10, 14], ["brewinandchewin:mead", 10, 14], ["brewinandchewin:egg_grog", 10, 14], ["brewinandchewin:glittering_grenadine", 10, 14], ["brewinandchewin:bloody_mary", 12, 22], ["brewinandchewin:salty_folly", 12, 22], ["brewinandchewin:pale_jane", 12, 22], ["brewinandchewin:saccharine_rum", 12, 22], ["brewinandchewin:strongroot_ale", 12, 22], ["brewinandchewin:dread_nog", 12, 22], ["brewinandchewin:kombucha", 14, 22], ["brewinandchewin:red_rum", 14, 22], ["brewinandchewin:steel_toe_stout", 14, 22], ["collectorsreap:pink_limeade", 8, 10], ["collectorsreap:berry_limeade", 8, 13], ["collectorsreap:limeade", 8, 13], ["collectorsreap:pink_limeade", 8, 13], ["collectorsreap:pomegranate_black_tea", 10, 14], ["collectorsreap:lime_green_tea", 10, 14], ["toughasnails:dirty_water_bottle", 6, 8], ["toughasnails:purified_water_bottle", 8, 10], ["toughasnails:leather_dirty_water_canteen", 8, 10], ["toughasnails:leather_water_canteen", 9, 11], ["toughasnails:leather_purified_water_canteen", 10, 12], ["toughasnails:copper_dirty_water_canteen", 8, 10], ["toughasnails:copper_water_canteen", 9, 11], ["toughasnails:copper_purified_water_canteen", 10, 12], ["toughasnails:iron_dirty_water_canteen", 8, 10], ["toughasnails:iron_water_canteen", 9, 11], ["toughasnails:iron_purified_water_canteen", 10, 12], ["toughasnails:gold_dirty_water_canteen", 8, 10], ["toughasnails:gold_water_canteen", 9, 11], ["toughasnails:gold_purified_water_canteen", 10, 12], ["toughasnails:diamond_dirty_water_canteen", 8, 10], ["toughasnails:diamond_water_canteen", 9, 11], ["toughasnails:diamond_purified_water_canteen", 10, 12], ["toughasnails:netherite_dirty_water_canteen", 8, 10], ["toughasnails:netherite_water_canteen", 9, 11], ["toughasnails:netherite_purified_water_canteen", 10, 12], ["toughasnails:melon_juice", 8, 13], ["toughasnails:apple_juice", 8, 13], ["toughasnails:cactus_juice", 8, 13], ["toughasnails:carrot_juice", 8, 13], ["toughasnails:glow_berry_juice", 8, 13], ["toughasnails:chorus_fruit_juice", 8, 13], ["toughasnails:suspicious_water_cup", 8, 13], ["toughasnails:pumpkin_juice", 8, 13], ["toughasnails:sweet_berry_juice", 8, 13], ["toughasnails:ice_cream", 6, 12]]

[Foods]
	#Defines items that will recover thirst when eaten
	#Format: [["item-id-1", hydration-amount, quenching-amount], ["item-id-2", hydration-amount, quenching-amount], ...etc]
	foods = [
  ["croptopia:artichoke", 1, 1],
  ["croptopia:asparagus", 2, 1],
  ["croptopia:basil", 1, 1],
  ["croptopia:bellpepper", 2, 1],
  ["croptopia:blackberry", 2, 1],
  ["croptopia:broccoli", 2, 1],
  ["croptopia:cabbage", 2, 1],
  ["croptopia:cantaloupe", 2, 2],
  ["croptopia:cauliflower", 2, 1],
  ["croptopia:celery", 2, 2],
  ["croptopia:chilepepper", 2, 1],
  ["croptopia:corn", 1, 1],
  ["croptopia:cucumber", 2, 2],
  ["croptopia:currant", 2, 1],
  ["croptopia:eggplant", 2, 1],
  ["croptopia:elderberry", 2, 1],
  ["croptopia:garlic", 1, 1],
  ["croptopia:grape", 2, 3],
  ["croptopia:greenbean", 2, 1],
  ["croptopia:greenonion", 2, 1],
  ["croptopia:honeydew", 2, 2],
  ["croptopia:kale", 1, 1],
  ["croptopia:kiwi", 2, 1],
  ["croptopia:leek", 2, 1],
  ["croptopia:lettuce", 2, 2],
  ["croptopia:olive", 1, 1],
  ["croptopia:onion", 2, 1],
  ["croptopia:pineapple", 2, 1],
  ["croptopia:radish", 2, 1],
  ["croptopia:rutabaga", 1, 1],
  ["croptopia:saguaro", 2, 2],
  ["croptopia:spinach", 2, 1],
  ["croptopia:squash", 2, 1],
  ["croptopia:strawberry", 2, 3],
  ["croptopia:sweetpotato", 1, 1],
  ["croptopia:tomatillo", 2, 1],
  ["croptopia:tomato", 2, 3],
  ["croptopia:turnip", 2, 1],
  ["croptopia:yam", 1, 1],
  ["croptopia:zucchini", 2, 2],
  ["croptopia:apricot", 2, 1],
  ["croptopia:avocado", 1, 1],
  ["croptopia:banana", 2, 1],
  ["croptopia:cherry", 2, 1],
  ["croptopia:coconut", 2, 1],
  ["croptopia:dragonfruit", 2, 3],
  ["croptopia:fig", 2, 1],
  ["croptopia:grapefruit", 2, 3],
  ["croptopia:kumquat", 2, 1],
  ["croptopia:lemon", 2, 2],
  ["croptopia:lime", 2, 2],
  ["croptopia:mango", 2, 1],
  ["croptopia:nectarine", 2, 1],
  ["croptopia:orange", 2, 3],
  ["croptopia:peach", 2, 3],
  ["croptopia:pear", 2, 3],
  ["croptopia:persimmon", 2, 1],
  ["croptopia:plum", 2, 3],
  ["croptopia:starfruit", 2, 3],
  ["croptopia:anchovy", 2, 1],
  ["croptopia:calamari", 2, 1],
  ["croptopia:clam", 2, 2],
  ["croptopia:crab", 2, 1],
  ["croptopia:glowingcalamari", 2, 1],
  ["croptopia:oyster", 2, 2],
  ["croptopia:roe", 1, 1],
  ["croptopia:shrimp", 2, 1],
  ["croptopia:tuna", 2, 1],
  ["croptopia:bakedbeans", 2, 1],
  ["croptopia:bakedsweetpotato", 1, 1],
  ["croptopia:bakedyam", 1, 1],
  ["croptopia:cookedanchovy", 2, 1],
  ["croptopia:cookedbacon", 1, 1],
  ["croptopia:cookedcalamari", 2, 1],
  ["croptopia:cookedshrimp", 2, 1],
  ["croptopia:cookedtuna", 2, 1],
  ["croptopia:applejuice", 5, 6],
  ["croptopia:cranberryjuice", 5, 6],
  ["croptopia:grapejuice", 5, 6],
  ["croptopia:melonjuice", 5, 6],
  ["croptopia:orangejuice", 5, 6],
  ["croptopia:pineapplejuice", 5, 6],
  ["croptopia:saguarojuice", 5, 6],
  ["croptopia:tomatojuice", 5, 6],
  ["croptopia:apricotjam", 3, 4],
  ["croptopia:blackberryjam", 3, 4],
  ["croptopia:blueberryjam", 3, 4],
  ["croptopia:cherryjam", 3, 4],
  ["croptopia:elderberryjam", 3, 4],
  ["croptopia:grapejam", 3, 4],
  ["croptopia:peachjam", 3, 4],
  ["croptopia:raspberryjam", 3, 4],
  ["croptopia:strawberryjam", 3, 4],
  ["croptopia:bananasmoothie", 5, 6],
  ["croptopia:strawberrysmoothie", 5, 6],
  ["croptopia:mangoicecream", 7, 14],
  ["croptopia:pecanicecream", 7, 14],
  ["croptopia:strawberryicecream", 7, 14],
  ["croptopia:vanillaicecream", 7, 14],
  ["croptopia:applepie", 4, 5],
  ["croptopia:cherrypie", 4, 5],
  ["croptopia:pecanpie", 4, 5],
  ["croptopia:rhubarbpie", 4, 5],
  ["croptopia:oliveoil", 2, 2],
  ["croptopia:cheese", 2, 2],
  ["croptopia:cheese", 1, 1],
  ["croptopia:tofu", 2, 1],
  ["croptopia:soysauce", 2, 2],
  ["croptopia:ravioli", 2, 1],
  ["croptopia:salsa", 5, 6],
  ["croptopia:antichokedip", 3, 4],
  ["croptopia:coffee", 5, 6],
  ["croptopia:lemonade", 5, 6],
  ["croptopia:limeade", 5, 6],
  ["croptopia:soymilk", 5, 6],
  ["croptopia:kalesmoothie", 14, 20],
  ["croptopia:fruitsmoothie", 7, 10],
  ["croptopia:chocolatemilkshake", 7, 10],
  ["croptopia:beer", 7, 10],
  ["croptopia:wine", 7, 10],
  ["croptopia:mead", 7, 10],
  ["croptopia:rum", 7, 10],
  ["croptopia:pumpkinspicelatte", 7, 10],
  ["croptopia:waterbottle", 1, 1],
  ["croptopia:milkbottle", 1, 1],
  
  [
    "minecraft:apple",
    2,
    3
  ],
  [
    "minecraft:golden_apple",
    2,
    3
  ],
  [
    "minecraft:enchanted_golden_apple",
    2,
    3
  ],
  [
    "minecraft:melon_slice",
    4,
    5
  ],
  [
    "minecraft:carrot",
    1,
    2
  ],
  [
    "minecraft:mushroom_stew",
    2,
    3
  ],
  [
    "minecraft:rabbit_stew",
    2,
    3
  ],
  [
    "minecraft:beetroot_soup",
    5,
    7
  ],
  [
    "minecraft:beetroot",
    1,
    2
  ],
  [
    "minecraft:sweet_berries",
    1,
    2
  ],
  [
    "minecraft:glow_berries",
    1,
    2
  ],
  [
    "minecraft:golden_carrot",
    1,
    2
  ],
  [
    "farmersdelight:pumpkin_slice",
    2,
    1
  ],
  [
    "farmersdelight:cabbage_leaf",
    1,
    2
  ],
  [
    "farmersdelight:melon_popsicle",
    7,
    9
  ],
  [
    "farmersdelight:fruit_salad",
    6,
    8
  ],
  [
    "farmersdelight:tomato_sauce",
    4,
    5
  ],
  [
    "farmersdelight:mixed_salad",
    4,
    5
  ],
  [
    "farmersdelight:beef_stew",
    4,
    5
  ],
  [
    "farmersdelight:chicken_soup",
    4,
    5
  ],
  [
    "farmersdelight:vegetable_soup",
    4,
    5
  ],
  [
    "farmersdelight:fish_stew",
    4,
    5
  ],
  [
    "farmersdelight:pumpkin_soup",
    4,
    5
  ],
  [
    "farmersdelight:baked_cod_stew",
    4,
    5
  ],
  [
    "farmersdelight:noodle_soup",
    4,
    5
  ],
  [
    "collectorsreap:lime_slice",
    1,
    2
  ],
  [
    "collectorsreap:lime",
    2,
    3
  ],
  [
    "collectorsreap:portobello_rice_soup",
    6,
    8
  ],
  [
    "collectorsreap:lime_popsicle",
    7,
    9
  ]
]
	
[Blacklist]
	#A mod may have added thirst compatibility to an item via code. If you want to edit the thirst values
	#of that item, add an entry in one of the first two lists. If instead you want to remove thirst support for that item, add an entry in this list
	#Format: ["examplemod:example_item_1", "examplemod:example_item_2"]
	itemsBlacklist = ["examplemod:example_item_1", "examplemod:example_item_2"]

