#How much sack weight the default sack can hold (100 is roughly one item)
#Range: > 0
maxSackTypes = 1
#How much sack weight the default sack can hold (100 is roughly one item)
#Range: > 0
maxSackWeight = 25600
#How many separate stacks can be held in the sack
#Range: > 0
maxSackStacks = 64
#How many mixed stacks of arrows the quiver can hold
#Range: > 0
maxQuiverOccupancyStacks = 8
#How many separate stacks can be held in the quiver
#Range: > 0
maxQuiverStacks = 64

