#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 02 21:02:06 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=Nostalgia_v5.1.zip
enableShaders=false
