#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 06 20:11:49 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=Nostalgia_v5.1.zip
enableShaders=false
